# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Jinkings Financiamento' do

pod 'RPFloatingPlaceholders'
pod 'CRToast'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'AFNetworking'

end

target 'Jinkings FinanciamentoTests' do

end

