# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Jinkings Soluciona' do

pod 'RPFloatingPlaceholders'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'TSMessages'

end
